spring:
  datasource:
    url: jdbc:mysql://${mysql_host:localhost}:${mysql_port:3306}/${mysql_db:imamba}?characterEncoding=utf8
    username: ${mysql_username:root}
    password: ${mysql_passwd:admin123}
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.mamba.cig.cigbiz.dao: info
    root: ${loggingLevel:info}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
